/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:52bb7b3d-faae-42ec-aa74-93601f770a52",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xnD7YKtfq",
    "aws_user_pools_web_client_id": "6unhs99urmp023dh70egt58lst",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://n334t7wllfasxc6nmjcmwfgjzi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cjnvdx4fq5aphjvof3g6vsklla",
    "aws_user_files_s3_bucket": "mdgmockportal9b546c8155164be78261159df6fd2770144022-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
