/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:52bb7b3d-faae-42ec-aa74-93601f770a52",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xnD7YKtfq",
    "aws_user_pools_web_client_id": "6unhs99urmp023dh70egt58lst",
    "oauth": {}
};


export default awsmobile;
